apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillayer.fullname" . }}-config
data:
  DEPLOYMENT_MODE: {{ .Values.config.deploymentMode | quote }}
  GITHUB_APP_ID: {{ .Values.config.githubAppId | quote }}
