apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillayer.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "skillayer.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "skillayer.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "skillayer.fullname" . }}-config
            - secretRef:
                name: {{ include "skillayer.fullname" . }}-secret
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
