apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillayer.fullname" . }}-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  selector:
    app: {{ include "skillayer.fullname" . }}-api
