"""Skilgen package."""

from skilgen.agents import fingerprint_project
from skilgen.delivery import run_delivery
from skilgen.sdk import (
    activate_skill_source,
    analyze_project,
    cancel_job,
    deactivate_skill_source,
    detect_skill_sources,
    deliver_project,
    get_job_status,
    init_project,
    install_skill_source,
    list_active_skill_sources,
    list_project_jobs,
    list_skill_sources,
    map_codebase,
    plan_project,
    preview_project,
    project_report,
    project_status,
    rank_skill_sources,
    remove_skill_source,
    resume_job,
    show_skill_source,
    skill_source_lock,
    skill_source_policy,
    start_deliver_job,
    sync_all_skill_sources,
    sync_skill_source,
    update_project,
    validate_project_outputs,
    watch_project,
)

__version__ = "0.3.0"

__all__ = [
    "__version__",
    "activate_skill_source",
    "analyze_project",
    "cancel_job",
    "deactivate_skill_source",
    "detect_skill_sources",
    "deliver_project",
    "fingerprint_project",
    "get_job_status",
    "init_project",
    "install_skill_source",
    "list_active_skill_sources",
    "list_project_jobs",
    "list_skill_sources",
    "map_codebase",
    "plan_project",
    "preview_project",
    "project_report",
    "project_status",
    "rank_skill_sources",
    "remove_skill_source",
    "resume_job",
    "run_delivery",
    "show_skill_source",
    "skill_source_lock",
    "skill_source_policy",
    "start_deliver_job",
    "sync_all_skill_sources",
    "sync_skill_source",
    "update_project",
    "validate_project_outputs",
    "watch_project",
]
